version: "3.8"

services:
  php:
    build: .
    container_name: php_fpm
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./app:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
